PKG_CONFIG = :
SDL_CONFIG = :
PNG_CONFIG = :

CC = emcc
CXX = em++

OPTS += -DEMSCRIPTEN -DTOUCHINPUTS -DNOWIPE

ifdef DEBUGMODE
TOTALMEMORY=101187584
else
TOTALMEMORY=99287040
endif

EMFLAGS = \
    -s USE_LIBPNG=1 \
    -s USE_SDL=2 \
    -s USE_SDL_MIXER=2 \
    -s USE_SDL_IMAGE=2 \
    -s USE_ZLIB=1 \
    -s TOTAL_MEMORY=$(TOTALMEMORY) \
    -s ALLOW_MEMORY_GROWTH=1 \
    -s EXIT_RUNTIME=1 \
    -lidbfs.js \
    -s EXPORTED_FUNCTIONS='["_main","_change_resolution","_inject_keycode"]' \
    -s EXTRA_EXPORTED_RUNTIME_METHODS='["ccall"]' \
    --preload-file ../assets@/ \
    --use-preload-cache \
    --shell-file ../srb2.html

ifdef DEBUGMODE
EMFLAGS+=-g3
endif

CFLAGS += $(EMFLAGS)
CPPFLAGS += $(EMFLAGS)
LDFLAGS += $(EMFLAGS)
