PKG_CONFIG = :
SDL_CONFIG = :
PNG_CONFIG = :

CC = emcc
CXX = em++

OPTS += -DEMSCRIPTEN

EMFLAGS = \
    -s USE_LIBPNG=1 \
    -s USE_SDL=2 \
    -s USE_SDL_MIXER=2 \
    -s USE_SDL_IMAGE=2 \
    -s USE_ZLIB=1 \
    -s TOTAL_MEMORY=99287040 \
    -s ALLOW_MEMORY_GROWTH=1 \
    -lidbfs.js \
    -s EXPORTED_FUNCTIONS='["_main","_emscripten_main"]' \
    -s EXTRA_EXPORTED_RUNTIME_METHODS='["ccall"]' \
    --preload-file ../assets@/ \
    --shell-file ../srb2.html

CFLAGS += $(EMFLAGS)
CPPFLAGS += $(EMFLAGS)
LDFLAGS += $(EMFLAGS)